INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오 뱅크', 15);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO BANK', 14);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오', 13);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO', 12);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오 페이', 11);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO PAY', 10);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오 모빌리티', 9);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO MOBILITY', 8);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오 페이지', 7);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO PAGE', 6);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오 게임즈', 5);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO GAMES', 4);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('카카오 웹툰', 3);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO WEBTOON', 2);
INSERT INTO T_SEARCH_WORD(SEARCH_WORD, SEARCH_COUNT) VALUES ('KAKAO ENTERPRISE', 1);



